### ISSUE TITLE
Ajout du service JWT Node JS au Docker Compose

### ISSUE THREAD

**Issue by jean-ely-gendrau** [jean-ely-gendrau/boutique-js#118]
# Ajout du service JWT Node JS au Docker Compose

## Contexte 🎛️ 
Un nouveau service, JWT Node JS, a été développé et doit être intégré à notre application. Ce service est responsable de la gestion des tokens JWT et doit être ajouté au fichier Docker Compose pour garantir son déploiement avec les autres services de l'application.

## Objectif 🚀 
Mettre à jour le fichier `docker-compose.yml` pour inclure le nouveau service JWT Node JS.

## Tâches 📄  

1. **Ajouter la définition du service JWT Node JS dans le `docker-compose.yml` :**
   - Définir l'image Docker à utiliser pour le service.
   - Spécifier les ports nécessaires.
   - Ajouter les variables d'environnement requises par le service.
   - Configurer les volumes si nécessaire.
   - Définir les dépendances et l'ordre de démarrage si applicable.

2. **Vérifier la connectivité avec les autres services :**
   - Assurer que le service JWT Node JS peut communiquer avec les services qui en ont besoin, par exemple, les services qui devront valider ou émettre des tokens JWT.

3. **Mettre à jour la documentation :**
   - Documenter le nouveau service et son intégration dans le Docker Compose.
   - Expliquer comment démarrer, arrêter et vérifier le bon fonctionnement du service.

4. **Tests :**
   - Effectuer des tests pour vérifier que le service JWT Node JS démarre correctement dans l'environnement Docker.
   - Tester les interactions entre le service JWT Node JS et les autres services de l'application.

## Critères d'acceptation 🔑  
- Le fichier `docker-compose.yml` contient la configuration du service JWT Node JS.
- Le service JWT Node JS démarre correctement avec Docker Compose.
- La documentation est à jour et explique clairement l'intégration du service.
- Les tests de connectivité et de fonctionnalité du service JWT Node JS avec les autres services sont concluants.

## Configuration du service pour `docker-compose.yml` 📦 

```yaml
version: '3.8'

services:
  node-jwt:
    hostname: teacoffee.dock
    restart: always
    secrets:
      - jwt_key
    build:
      context: ./node-jwt
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-jwt:/app
```
